default_install_hook_types:
  - pre-commit
  - commit-msg
default_stages: [pre-commit]
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-yaml
      - id: check-toml
      - id: check-json
  - repo: local
    hooks:
      - id: bun-lint
        name: bun run lint
        entry: bun run lint
        language: node
        types_or: [javascript, ts, svelte, json]
        pass_filenames: false
      - id: bun-check
        name: bun run check
        entry: bun run check
        language: node
        types_or: [javascript, ts, svelte, json]
        pass_filenames: false
      - id: bun-test
        name: bun run test
        entry: bun run test
        language: node
        types_or: [javascript, ts, svelte, json]
        pass_filenames: false
      - id: bun-build
        name: bun run build
        entry: bun run build
        language: node
        types_or: [javascript, ts, svelte, json]
        pass_filenames: false
